### ISSUE TITLE
Support publishing to master

### ISSUE THREAD

**Issue by chenglou** [facebook/Docusaurus#253]
We just converted https://github.com/BuckleScript/bucklescript.github.io to Docusaurus!

Except the workflow doesn't allow publishing to master. For an organization's page, we have no choice but to publish to the `orgname.github.io` repo's `master`branch. So right now we're publishing manually (copy paste artifacts & push)

**Comment by chimon2000** [comment]
I am running into the same issue.  After the first publish I get the following error:

```
fatal: A branch named 'master' already exists.
fatal: could not set upstream of HEAD to origin/master when it does not point to any branch.
```

**Comment by JoelMarcey** [comment]
@chimon2000 Hi! I believe this has been fixed, but I want to be sure. There is a note in https://docusaurus.io/docs/en/publishing.html#using-github-pages talking about how to publish to the `master` branch.  Have you seen that?

I want to try to get this working for you, since it definitely should.

**Comment by JoelMarcey** [comment]
Also, if there is a way we can describe how to do it better, definitely let us know. 

To be honest, I had hoped I could close this issue, but I had just forgotten. Hoping I can still close it. :)

**Comment by chimon2000** [comment]
@JoelMarcey thanks for the quick reply.

I'm assuming that you're referring to the following

> Docusaurus also supports deploying user or organization sites. Just set your project name to "username.github.io" (where username is your username or organization name on GitHub) and the publish script will automatically deploy your site to the root of the master branch instead.

After making those changes I was still seeing the same error.  It's possible that I just fudged something. 
 Here is what my siteConfig looks like:

```
/* List of projects/orgs using your project for the users page */

const users = []

const siteConfig = {
  title: 'CodeForCharlotte' /* title for your website */,
  tagline: 'Become an open source contributor in no time!!!',
  url: 'https://codeforcharlotte.github.io/' /* your website url */,
  baseUrl: '/' /* base url for your project */,
  projectName: 'codeforcharlotte.github.io',
  headerLinks: [
    {doc: 'getting_started', label: 'Docs'},
    {page: 'help', label: 'Help'},
    // {blog: true, label: 'Blog'},
  ],
  users,
  /* path to images for header/footer */
  favicon: 'img/CFC-favicon.png',
  /* colors for website */
  colors: {
    primaryColor: '#3d9cd1',
    secondaryColor: '#3d9cd1',
  },
  // This copyright info is used in /core/Footer.js and blog rss/atom feeds.
  copyright:
    'Copyright © ' +
    new Date().getFullYear() +
    ' CodeForCharlotte',
  organizationName: 'codeforcharlotte', // or set an env variable ORGANIZATION_NAME
  highlight: {
    // Highlight.js theme to use for syntax highlighting in code blocks
    theme: 'default',
  },
  scripts: ['https://buttons.github.io/buttons.js'],
  // You may provide arbitrary config keys to be used as needed by your template.
  repoUrl: 'https://github.com/CodeForCharlotte/codeforcharlotte.github.io',
};

module.exports = siteConfig;

```

**Comment by JoelMarcey** [comment]
Thanks for the `siteConfig.js` - I have a couple of things we can try here. It's possible I messed up the docs.

Can you try changing the `organizationName` to empty? 

e.g., 

'''
projectName: 'codeforcharlotte.github.io',
organizationName: '',
'''

and remove the `organizationName: 'codeforcharlotte', // or set an env variable ORGANIZATION_NAME` line.

**Comment by JoelMarcey** [comment]
Actually, I am looking at my site that I am using to test this. And I had something similar to your original. Let me make sure that works.

**Comment by JoelMarcey** [comment]
Ahh -- I just looked at your site.

https://github.com/codeforcharlotte/codeforcharlotte.github.io

So I think the problem is that you are trying to both have the docs in the `master` branch and publish to the `master` branch.

If you move the docs to a branch called `source` or something. And then try to publish to `master` it should work.

Check out:

https://github.com/JoelMarcey/joelmarcey.github.io

My default branch is called `source`. But I am publishing to `master`.

I probably should update the docs to make that more clear.

**Comment by chimon2000** [comment]
Ah, I see that makes sense.  I was under the impression that I was supposed to be housing both in the same repo.

**Comment by JoelMarcey** [comment]
I will update the documentation in that section to make it a bit more clear.

**Comment by chimon2000** [comment]
@JoelMarcey I can verify that changing the default repo works. Thank you!
