### ISSUE TITLE
Support custom prism languages

### ISSUE THREAD

**Issue by zepatrik** [facebook/docusaurus#4719]
## 🚀 Feature

I have a project where I defined my own prism language for the docs. I got it to work with docusaurus, but it is quite cumbersome:

1. Define language and add side-effect import to pollute the global prism instance: https://github.com/ory/keto/blob/43eab1d462837af5e4ad5b8a3c6db68b56e162a5/docs/src/theme/RelationTuplePrism.js
2. Import that **manually** in **every** page that requires the language just to ensure it is still loaded when the page is directly hit/reloaded: https://github.com/ory/keto/blob/43eab1d462837af5e4ad5b8a3c6db68b56e162a5/docs/docs/concepts/relation-tuples.mdx

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

My language is not yet mature or relevant enough to be added to prism itself. Another use case might be where someone wants to use an updated version of a language, that did not yet propagate up to docusaurus, or slightly modify an existing language.

## Pitch

I would like to extend #2250 and allow not only strings to be defined in the `additionalLanguages` array, but also raw language definitions. This way I can use my own definition:

```js
{
  ...docusaurusConfig,
  themeConfig: {
    prism: {
      additionalLanguages: ['shell-session', require('./my-awesome-language')]
    }
  }
}
```

I can come up with a PR if that feature is going to be merged.

**Comment by slorber** [comment]
You can already add a custom prism language definition by swizzling the file importing the languages:

https://docusaurus.io/docs/next/markdown-features/code-blocks#syntax-highlighting

![image](https://user-images.githubusercontent.com/749374/116900315-e41a3180-ac38-11eb-8850-44da9e772ab1.png)

Isn't this working for your use-case?

**Comment by zepatrik** [comment]
Hm somehow missed that documentation part. It should fix the problem. I will quickly try it, thx :sweat_smile:

**Comment by slorber** [comment]
if you missed it, others will too, so don't hesitate to improve the doc to make this clearer if needed ;)

**Comment by zepatrik** [comment]
Yes, works perfectly fine. I was searching in the wrong places, and probably with the wrong key words, so I will try to improve them.
