### ISSUE TITLE
Doc Sidebar is covering NavBar Buttons

### ISSUE THREAD

**Issue by fabrusso** [facebook/docusaurus#4826]
## 🐛 Bug Report

The navbar in the documentation page is not working.
Is correctly working in the Home page.

I checked the the HTML and It seems that the sidebar containing Doc link has a margin-top that is covering the buttons area.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Go to documentation
1. Try click on navbar "left positioned" button near the logo

## Expected behavior

I expect the buttons to redirect me to the url\src

## Actual Behavior

Buttons are not clickable

## Your Environment

- Docusaurus version used: @docusaurus/core": "^2.0.0-beta.0
- Environment name and version: Mozilla for Developers
- Operating system and version (desktop or mobile): MacOS BigSur

## Reproducible Demo

Doc to check:
https://crono.matchplat.io/docs/installation/installation

Current margin of the child DIV:
<img width="298" alt="Schermata 2021-05-21 alle 12 18 34" src="https://user-images.githubusercontent.com/25503491/119122526-e220e280-ba2e-11eb-9d4a-0b5ed8e5fb75.png">

Parent DIV covering:
<img width="484" alt="Schermata 2021-05-21 alle 12 21 41" src="https://user-images.githubusercontent.com/25503491/119122952-5f4c5780-ba2f-11eb-9621-e0e2b9678981.png">

Disabling that margin-top:
<img width="484" alt="Schermata 2021-05-21 alle 12 21 47" src="https://user-images.githubusercontent.com/25503491/119122976-65423880-ba2f-11eb-9e5f-8cabe071c0b9.png">

The Sidebar with no Margin Top and clickable buttons:
<img width="301" alt="Schermata 2021-05-21 alle 12 21 59" src="https://user-images.githubusercontent.com/25503491/119123018-6f643700-ba2f-11eb-9193-433fb2adde3b.png">

**Comment by lex111** [comment]
@fabrusso hi, could you please provide a reproducible repo or website link?

**Comment by fabrusso** [comment]
> @fabrusso hi, could you please provide a reproducible repo or website link?

https://crono.matchplat.io/docs/installation/installation

Thanks.

**Comment by mhwinkler** [comment]
I'm also experiencing this issue, it may be related to CSS minification.

When using the local server, my `/styles.css` contains:

```css
--ifm-z-index-dropdown: 100;
--ifm-z-index-fixed: 200;
--ifm-z-index-overlay: 400;
```

After a production build, the same lines read:
```css
--ifm-z-index-dropdown: #100;
--ifm-z-index-fixed: #200;
--ifm-z-index-overlay: #400;
```

**Comment by lex111** [comment]
This was fixed in PR https://github.com/cssnano/cssnano/pull/1122 @omgovich thanks for that!

@fabrusso @mhwinkler we have explicitly bumped the appropriate versions of CSS minification packages, but since we use caret ranges, you can simply reinstall dependencies of your site and remove previous build artifacts by running `yarn clear` command, after that the issue will be fixed.

**Comment by ishan-grubtech** [comment]
@lex111 when I run npm run start, this fix seems to be working. but when I do an npm run build followed npm run serve it's still broken.

**Comment by rrdelaney** [comment]
Also still happening to me 😕

**Comment by slorber** [comment]
@rrdelaney you are using cssnano@5.0.3, please make sure it's not the case anymore.

A good way is to re-generate your lockfile by deleting it, it will pick a newer (non-buggy) cssnano version
