### ISSUE TITLE
Html Entities inside inline SVG do not render correctly

### ISSUE THREAD

**Issue by blemelin** [facebook/docusaurus#5144]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description

Html entities inside inline svg does not render correctly. They seems to be escaped twice.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

Here are the steps to reproduce the issue.

1. Create a SVG with special characters like < or >.
1. Add it to any doc by inlining it (see [this](https://docusaurus.io/docs/markdown-features/assets#inline-svgs))

## Expected behavior

![image](https://user-images.githubusercontent.com/8997953/125201247-37fa5580-e23c-11eb-9611-f1697ab55922.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/8997953/125201233-2f098400-e23c-11eb-8887-4a5ae1c88be7.png)

For your information, I can use the `<img>` tag and it works just fine, but I need the text to be selectable (yeah...that's a weird requirement...I know....).

## Your environment

- Windows 10 Build 19042.1083
- Firefox 89.2.2
- NodeJs 7.3.0

## Reproducible demo

Live Demo : [Deleted]
Repo : [Deleted]
`intro.md` file : [Deleted]

**Comment by lex111** [comment]
Fix for this bug here -> https://github.com/gregberge/svgr/pull/553, so we will wait for merge that.

**Comment by Josh-Cena** [comment]
Should be fixed

**Comment by lex111** [comment]
Actually, this is not fixed. However, a new major version (in alpha stage) of svgr/webpack has been released which fixes this issue. Therefore, @blemelin you can upgrade your local dependency "@svgr/webpack" to "v6.0.0-alpha.0" to resolve the bug. We on our part, will wait for more stable version.

**Comment by Josh-Cena** [comment]
In that case let's reopen & wait for the version bump on our side🤷‍♂️

**Comment by lex111** [comment]
Resolved in #5958.

However since @svgr/webpack dependency is explicitly listed in the package.json when initializing of Docusaurus site, this library   must be manually updated to "^6.0.0".

**Comment by Josh-Cena** [comment]
> However since @svgr/webpack dependency is explicitly listed in the package.json when initializing of Docusaurus site, this library must be manually updated to "^6.0.0".

I _guess_ it's actually fine, because in our core we prioritize `node_modules` of the core itself to the site's `node_modules` so that the deps is always the version required by the core
