### ISSUE TITLE
TypeError when building project, after upgrading to v2.0.0-beta.19

### ISSUE THREAD

**Issue by becca-tiessen** [facebook/docusaurus#7398]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

While upgrading our project to from Docusaurus v2.0.0-beta.18 to v2.0.0-beta.19 we are now encountering an issue during the build.

### Steps to reproduce

1. Upgrade docusaurus using the command `npm i @docusaurus/core@2.0.0-beta.19 @docusaurus/preset-classic@2.0.0-beta.19 @docusaurus/module-type-aliases@2.0.0-beta.19` from v2.0.0-beta-18
2. `npm run build`

### Expected behavior

To have no problems building. The `chalk_1.default.bold` TypeError doesn't seem related to any breaking changes introduced in the beta-19 version and there are no existing related issues either.

### Actual behavior

To upgrade, we ran `npm i @docusaurus/core@2.0.0-beta.19 @docusaurus/preset-classic@2.0.0-beta.19 @docusaurus/module-type-aliases@2.0.0-beta.19`.

Then when running `npm run build` we run into the below output:

```
TypeError: chalk_1.default.bold is not a function
TypeError: chalk_1.default.bold is not a function
TypeError: chalk_1.default.bold is not a function
TypeError: chalk_1.default.bold is not a function
TypeError: chalk_1.default.bold is not a function
TypeError: chalk_1.default.bold is not a function
TypeError: chalk_1.default.bold is not a function
... (many more times)
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/@babel/core/lib/config/files/configuration.js","moduleName":"./node_modules/@babel/core/lib/config/files/configuration.js","loc":"163:150-157","message":"Critical dependency: require function is used in a way in which dependencies cannot be statically extracted","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/@babel/core/lib/config/files/import.js","moduleName":"./node_modules/@babel/core/lib/config/files/import.js","loc":"9:9-25","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/@babel/core/lib/config/files/module-types.js","moduleName":"./node_modules/@babel/core/lib/config/files/module-types.js","loc":"89:17-34","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/@babel/core/lib/config/files/plugins.js","moduleName":"./node_modules/@babel/core/lib/config/files/plugins.js","loc":"148:144-151","message":"Critical dependency: require function is used in a way in which dependencies cannot be statically extracted","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/@babel/helper-define-polyfill-provider/lib/node/dependencies.js","moduleName":"./node_modules/@babel/helper-define-polyfill-provider/lib/node/dependencies.js","loc":"32:13-20","message":"Critical dependency: require function is used in a way in which dependencies cannot be statically extracted","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/@babel/helper-define-polyfill-provider/lib/node/dependencies.js","moduleName":"./node_modules/@babel/helper-define-polyfill-provider/lib/node/dependencies.js","loc":"54:6-13","message":"Critical dependency: require function is used in a way in which dependencies cannot be statically extracted","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/@svgr/core/dist/index.js","moduleName":"./node_modules/@svgr/core/dist/index.js","loc":"159:33-52","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/browserslist/node.js","moduleName":"./node_modules/browserslist/node.js","loc":"171:18-76","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/browserslist/node.js","moduleName":"./node_modules/browserslist/node.js","loc":"171:26-33","message":"Critical dependency: require function is used in a way in which dependencies cannot be statically extracted","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/browserslist/node.js","moduleName":"./node_modules/browserslist/node.js","loc":"192:16-195:6","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/browserslist/node.js","moduleName":"./node_modules/browserslist/node.js","loc":"192:24-31","message":"Critical dependency: require function is used in a way in which dependencies cannot be statically extracted","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/import-fresh/index.js","moduleName":"./node_modules/import-fresh/index.js","loc":"32:31-48","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/svgo/lib/svgo-node.js","moduleName":"./node_modules/svgo/lib/svgo-node.js","loc":"22:13-32","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/svgo/lib/svgo-node.js","moduleName":"./node_modules/svgo/lib/svgo-node.js","loc":"27:42-75","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/svgo/lib/svgo-node.js","moduleName":"./node_modules/svgo/lib/svgo-node.js","loc":"32:17-36","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[WARNING] {"moduleIdentifier":"/Users/rebecca.tiessen/workspace/developer-docs/node_modules/url-loader/dist/index.js","moduleName":"./node_modules/url-loader/dist/index.js","loc":"120:19-42","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/rebecca.tiessen/workspace/developer-docs/node_modules/@docusaurus/core/lib/webpack/utils.js:182:24
    at /Users/rebecca.tiessen/workspace/developer-docs/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/rebecca.tiessen/workspace/developer-docs/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

![Screen Shot 2022-05-10 at 4 21 06 PM](https://user-images.githubusercontent.com/23246768/167726712-5a0301c0-8ae9-441b-823d-3927b31614d4.png)

Apologies for not creating a reproducible demo, if that's necessary to get this looked at then we can potentially schedule it into our work flow but we've spent a good amount of work time trying to debug this already. Thanks in advance if you're able to provide any insights!

### Your environment

- Public source code: n/a (not public)
- Public site URL: https://developer.boldcommerce.com/default/
- Docusaurus version used: 2.0.0-beta-18
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.3
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Monterey 12.3.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by sserrata** [comment]
For what it's worth, we encountered a similar issue when attempting to upgrade our plugin from beta.18 to beta.19 and then beta.20. Seeing same exact errors. Can reproduce it and link to a PR if it could be helpful?

**Comment by becca-tiessen** [comment]
That would definitely be helpful, our repo is private so to create a demo with the issue reproduced will likely take some time. Thanks!

**Comment by sserrata** [comment]
## Reproduces Type Errors Observed in 2.0.0-beta.20

PR: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/81
Build output: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/runs/6396242136?check_suite_focus=true

For some reason, I'm seeing the `TypeError: chalk_1.default.bold is not a function` error despite upgrading to `2.0.0-beta.20`. However, I have been able to reproduce the `TypeError: content.replace is not a function` error locally, after adding `nohoist` to my lerna workspace demo site.

**Comment by aerovulpe** [comment]
I believe this issue is affecting the redocusaurus plugin too. 

https://github.com/rohit-gohri/redocusaurus/issues/175

**Comment by Josh-Cena** [comment]
Thanks @sserrata I will start with your isolated repro with the `content.replace` issue. The `chalk_1.default` one is very unstable and re-installing almost always fixes, so it's relatively low-priority.

**Comment by Josh-Cena** [comment]
Can I get a confirmation that everyone running into this issue is using some kind of redoc/open API plugin?

**Comment by sserrata** [comment]
> Can I get a confirmation that everyone running into this issue is using some kind of redoc/open API plugin? I did some preliminary hacks and found that the `content.replace` problem is coming from a `stripBom` function, which does not sound familiar to me.

We are indeed running an OpenAPI plugin although the error occurs only when we include the accompanying theme (since the plugin only extends the docusaurus CLI). 

I ran `yarn why strip-bom-string` and it seems to be introduced by `@docusaurus/utils` via the `gray-matter` package.

```bash
yarn why v1.22.18
[1/4] 🤔  Why do we have the module "strip-bom-string"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "strip-bom-string@1.0.0"
info Reasons this module exists
   - "_project_#docusaurus-plugin-openapi-docs#@docusaurus#utils#gray-matter" depends on it
   - Hoisted from "_project_#docusaurus-plugin-openapi-docs#@docusaurus#utils#gray-matter#strip-bom-string"
info Disk size without dependencies: "16KB"
info Disk size with unique dependencies: "16KB"
info Disk size with transitive dependencies: "16KB"
info Number of shared dependencies: 0
```

**Comment by becca-tiessen** [comment]
> Can I get a confirmation that everyone running into this issue is using some kind of redoc/open API plugin? I did some preliminary hacks and found that the `content.replace` problem is coming from a `stripBom` function, which does not sound familiar to me.

Can confirm, we're also using redocusaurus!

**Comment by rohit-gohri** [comment]
> The chalk_1.default one is very unstable and re-installing almost always fixes, so it's relatively low-priority.

@Josh-Cena  I've been trying to fix this on the redocusaurus side today. And for me this is the error troubling me, even on a fresh install. Build Logs: https://github.com/rohit-gohri/redocusaurus/runs/6432967265?check_suite_focus=true

PR open here: https://github.com/rohit-gohri/redocusaurus/pull/176

It seems every time there is a new beta it breaks my plugin. Is there anyway we can declare compatibility with docusaurus versions in the plugin's package.json?

**Comment by Josh-Cena** [comment]
> Is there anyway we can declare compatibility with docusaurus versions in the plugin's package.json?

There isn't an official way to do this, but you can import `@docusaurus/core/package.json` to read its version.

> It takes quite some time and effort to support the latest beta and fix the builds.

I'm still not sure if it's a Docusaurus bug or a bug in redocusaurus yet...

**Comment by rohit-gohri** [comment]
> I'm still not sure if it's a Docusaurus bug or a bug in redocusaurus yet...

It was an issue in `redocusaurus`, I've released a new release with the fix: https://github.com/rohit-gohri/redocusaurus/releases/tag/v1.0.3

But there is some issue in Docusaurus too because the error was due to `[ERR_INVALID_URL]: Invalid URL`, but this was not showing up due to chalk errors.

**Comment by Josh-Cena** [comment]
> but this was not showing up due to chalk errors.

Yeah, the chalk error only shows up when SSR throws because of some other error. It doesn't reproduce consistently, so I can't say what's wrong. Hopefully, when we emit ESM code during SSR (which will not be very distant), this will be gone since we won't worry about all the interop mess :)

**Comment by mmartev** [comment]
Seems to be ok with 1.0.4 of redocusaurus, my project now builds ok.

**Comment by markkane** [comment]
We are having the same problem when moving our code to a version of docusaurus > than beta.18. SSR builds to 92%, then:

```
[the next line x30]
[ERROR] Docusaurus server-side rendering could not render static page with path "/docs/roadmap".

TypeError: content.replace is not a function
[the previous line x30]
```

We do not use redocusaurus, but we do use another OpenAPI Module called RapiDoc (wrapped in BrowserOnly).

**Comment by Josh-Cena** [comment]
From https://github.com/rohit-gohri/redocusaurus/pull/178, it looks like @rohit-gohri fixed it by adding the `tty` polyfill? I'm not sure what we need to do on our side, since the bug with redocusaurus is indeed fixed without us doing anything.

**Comment by markkane** [comment]
I wish I could give more useful information. We have `docusaurus-node-polyfills` in our project, which includes tty, so I don't think that is causing our problems. I even tried reproducing the `tty` fix in the PR you linked, but it doesn't change anything for us.

All I can say for sure is our build breaks when upgrading from beta.18 -> beta.19 or beta.20. No other changes on our side. Maybe another plugin or customization is involved or even the cause, but upgrading docusaurus triggers the problem and apparently it doesn't only happen for projects using redocusaurus.

**Comment by rohit-gohri** [comment]
> it looks like @rohit-gohri fixed it by adding the tty polyfill

That was a side-effect actually, the real error was the `TypeError [ERR_INVALID_URL]: Invalid URL` thrown from redoc. Added the full explanation here: https://github.com/rohit-gohri/redocusaurus/issues/175#issuecomment-1126668780 

> I'm not sure what we need to do on our side
I think `TypeError: content.replace is not a function` is not the real error that fails the build and docusaurus for some reason can't print the actual error and throws this.

**Comment by Josh-Cena** [comment]
The only place in Docusaurus with `content.replace` that could choke SSR is our code block:

https://github.com/facebook/docusaurus/blob/b7448865fe78ae1ed7585f9793ffeebd7a75a52f/packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts#L160

But it has been like that in a while, so I'm almost optimistic that it's not the culprit. The hypothesis that it's coming from `gray-matter` doesn't make a lot of sense, because `gray-matter` is run on server-side, but if it fails at that time, the SSR process shouldn't even be able to start at all!

It's always been painful that SSR doesn't print the stack traces. We can only work backwards.

**Comment by becca-tiessen** [comment]
> If it's fixed, can I close this now? I'd like the folks who joined this thread to give a confirmation that the latest patch fixes everything. 

The redocusaurus update to 1.1.0 fixed it for us! Thanks everyone for hopping on and figuring this out! 🥇

**Comment by Josh-Cena** [comment]
> instead of `TypeError: content.replace is not a function` I am seeing the original `TypeError: chalk_1.default.bold is not a function` error,

_Sigh_ I'm tempted to say that `TypeError: content.replace is not a function` and `TypeError: chalk_1.default.bold is not a function` are both garbage messages. I'm pretty confident to say that the `chalk_1.default.bold` error is due to a bad `tslib` behavior with `__importDefault` in our SSR pipeline. For `content.replace`, I still have zero idea where it's coming from.

> any other suggestions for how we can derive the real error being thrown

I suggest reducing the build to one page that still reproduces the error, then doing a binary search on your source to see which part causes the error. If you can make a minimal repro for me to look at, I can also take a try.

**Comment by rohit-gohri** [comment]
> any other suggestions for how we can derive the real error being thrown? 

@sserrata You can use the debugger to break at caught exceptions when the server build is about to complete. I followed this: https://indepth.dev/posts/1166/this-will-make-you-more-efficient-at-debugging-webpack-unspecified-build-errors


I tried for the minimal repo and got this as the error that triggers the build failure:

```
Hook useTabGroupChoice is called outside the <TabGroupChoiceProvider>.
ReactContextError
    at useTabGroupChoice (main:38645:1282)
    at ResponseCodeTabs (main:56136:584)
    at d (main:118177:498)
    at bb (main:118180:16)
    at a.b.render (main:118186:43)
    at a.b.read (main:118185:83)
    at Object.exports.renderToString (main:118196:138)
    at doRender (main:29440:417)
    at async serverEntry_render (main:29437:290)
```

@Josh-Cena This is the call stack for the `content.replace` issue:
```
stripBom (<node_internals>/main:89284)
_readFile (<node_internals>/main:89198)
async function (Unknown Source:1)
_readFile (<node_internals>/main:130054)
doRender (<node_internals>/main:29441)
async function (Unknown Source:1)
serverEntry_render (<node_internals>/main:29437)
<anonymous> (/Users/user/Projects/docusaurus-type-error/node_modules/@slorber/static-site-generator-webpack-plugin/index.js:78)
renderPaths (/Users/user/Projects/docusaurus-type-error/node_modules/@slorber/static-site-generator-webpack-plugin/index.js:64)
<anonymous> (/Users/user/Projects/docusaurus-type-error/node_modules/@slorber/static-site-generator-webpack-plugin/index.js:53)
fn (/Users/user/Projects/docusaurus-type-error/node_modules/webpack/lib/Compilation.js:509)
_next0 (<eval>/VM46948915:32)
eval (<eval>/VM46948915:49)
eval (<eval>/VM46948916:6)
CALL_ASYNC_DELEGATE (/Users/user/Projects/docusaurus-type-error/node_modules/tapable/lib/Hook.js:18)
<anonymous> (/Users/user/Projects/docusaurus-type-error/node_modules/webpack/lib/Compilation.js:515)
<anonymous> (/Users/user/Projects/docusaurus-type-error/node_modules/copy-webpack-plugin/dist/index.js:909)
async function (Unknown Source:1)
fn (/Users/user/Projects/docusaurus-type-error/node_modules/webpack/lib/Compilation.js:509)
eval (<eval>/VM46948915:44)
```

It seems to be coming from https://github.com/slorber/static-site-generator-webpack-plugin

And I think reason it's happening for openapi plugins maybe because of the Buffer polyfill most of them are using?
Because the runtime value of `content` in `content.replace` is still a Buffer and that is why `replace is not a function`. The `Buffer.isBuffer` check in `stripBom` fails.

**Comment by Josh-Cena** [comment]
@rohit-gohri How the SSG plugin works is, it first builds your entire SPA into a single bundle, then run that bundle, which contains a `ReactDOM.renderToString` call, in Node.js, and writes the output to disk. Therefore, every single build time error will be coming from `@slorber/static-site-generator-webpack-plugin` because that's where the SSR process starts. (And you can see that further above it's coming from `doRender` which tells you it's from the bundle itself instead of the plugin malbehaving)

**Comment by sserrata** [comment]
```bash
Hook useTabGroupChoice is called outside the <TabGroupChoiceProvider>.
```

Thanks @rohit-gohri! The strange thing is that this error was previously showing up in dev server, but seemed to be resolved after we migrated from `FrontMatter` to `DocFrontMatter` type (not sure how they'd be related). Either way, we'll add `TabGroupChoiceProvider` and will respond with the results.

**Comment by sserrata** [comment]
@rohit-gohri, my bad. I just realized my minimal repro was still referencing the old version of the plugin/theme that still depended on 2.0.0-beta.18. That would explain the provider error(s). I'm pushing a change to the minimal repro repo that now includes a canary release with support for 2.0.0-beta.20. You can upgrade in place by bumping the following:

```
    "docusaurus-plugin-openapi-docs": "0.0.0-349",
    "docusaurus-theme-openapi-docs": "0.0.0-349",
```

**Comment by sserrata** [comment]
> And I think reason it's happening for openapi plugins maybe because of the Buffer polyfill most of them are using?
Because the runtime value of content in content.replace is still a Buffer and that is why replace is not a function. The Buffer.isBuffer check in stripBom fails.

I tested by adding `Buffer.isBuffer(content)` and `typeof content` to `codeBlockUtils.js` and confirmed that all content is indeed a `string`.

**Comment by Josh-Cena** [comment]
@sserrata Thanks a lot for that information! 0.0.0-4875 is https://github.com/facebook/docusaurus/pull/7186, which does look like there's a chance of breaking the build.

I would look into this. Thanks again! Much appreciated.

**Comment by sserrata** [comment]
> If you are interested in investigating further, you can try replacing await fs.readJSON(manifestPath) in node_modules/@docusaurus/core/lib/client/serverEntry.js with JSON.parse(await fs.readFile(manifestPath, 'utf8')) and see if it fixes your error.

@Josh-Cena Yes, that appears to have fixed the error. With that fix I was able to work my way up to [0.0.0-4893](https://www.npmjs.com/package/@docusaurus/core/v/0.0.0-4893) before encountering a new error in [0.0.0-4894](https://www.npmjs.com/package/@docusaurus/core/v/0.0.0-4894):

```bash
Attempted import error: 'decodedMap' is not exported from '@jridgewell/gen-mapping' (imported as 'decodedMap').
Attempted import error: 'encodedMap' is not exported from '@jridgewell/gen-mapping' (imported as 'encodedMap').
TypeError: Cannot read properties of undefined (reading 'split')
```

**Comment by markkane** [comment]
> @sserrata If you are interested in investigating further, you can try replacing `await fs.readJSON(manifestPath)` in `node_modules/@docusaurus/core/lib/client/serverEntry.js` with `JSON.parse(await fs.readFile(manifestPath, 'utf8'))` and see if it fixes your error.

Thanks @Josh-Cena: changing this line fixes the build errors for me. Site builds normal in beta.20 now locally, doesn't fix the pipeline of course.

**Comment by ckailash** [comment]
I just wanted to chime in and say that I'm using https://github.com/stoplightio/elements/, and I'm running into the same issue discussed here!

**Comment by snikch** [comment]
I'm another user of Stoplight Elements with this issue.

**Comment by Josh-Cena** [comment]
I think the culprit here is indeed about the `Buffer` polyfill. The error is thrown from here: https://github.com/jprichardson/node-jsonfile/blob/a5414d716dd5ea21aa9327bdebaefa75f0bcf5d1/utils.js#L8-L12 (which is called by `fs.readJSON`, which I recommended to replace above). The reason is because during SSR, `Buffer` is already available in the global scope and doesn't need to be polyfilled. I don't know how these polyfills are applied and whether they check existing globals first, but indeed `Buffer.isBuffer(content)` returned `false` even when the file is actually still a buffer.

I'm going to avoid using `logger` and `readJSON` in server entry, but ideally we should figure out a better way to do this.

**Comment by rohit-gohri** [comment]
I think the polyfill is only replacing the `require('buffer')` calls and not the global Buffer. If we add polyfill for both (module and global) then it might be fixed?

**Comment by Josh-Cena** [comment]
In any case, I've merged https://github.com/facebook/docusaurus/pull/7453 which avoids using some "risky" globals in SSR. I'm hoping 0.0.0-5034 would fix the error; I don't really want to think too deeply about this😄

**Comment by snikch** [comment]
Works for me :heart:

**Comment by Josh-Cena** [comment]
Great! Seems we've already have success stories from the majority, either because of @rohit-gohri's fix or from #7453. Specifically, I hope that the following errors no longer appear after using Canary:

- `TypeError: chalk_1.default.bold is not a function`
- `TypeError: content.replace is not a function`
- `TypeError [ERR_INVALID_URL]: Invalid URL`

I'm going to close this as resolved then. If there are any lingering errors just let me know below, and we can take another look.

**Comment by sibelius** [comment]
do we need to wait a new release to get the fix?

is there a patch package for this?

**Comment by Josh-Cena** [comment]
Please [use the canary release](https://docusaurus.io/community/canary). (We have been talking about canary a lot above)

**Comment by sserrata** [comment]
Works for our plugin as well! Thanks again for everyone's help! 🥳

**Comment by sgrund14** [comment]
I was getting the `chalk_1.default.bold is not a function` error but I just fixed it 😄 

the problem was this polyfill code which I had in a component definition file after the initial imports (so run on the server)

```
if (!window.Buffer) {
  window.Buffer = Buffer;
}
```

I fixed it by updating it to 
```
if (typeof window !== "undefined" && !window.Buffer) {
  window.Buffer = Buffer;
}
```
guess it makes sense that `window` would be undefined on the server but yes the error message was a bit confusing 😅

**Comment by alirezamirian** [comment]
I'm still experiencing this issue. Tried `beta.20` and `beta.21` as well. Tried `yarn clear` and removing `yarn.lock` file too.

**Comment by markerikson** [comment]
I just tried upgrading Redux Toolkit's website from `beta.7` to `beta.21`, and I'm seeing a variation on this error as well:

```
TypeError: source_default(...).bold is not a function
TypeError: source_default(...).bold is not a function
TypeError: source_default(...).bold is not a function
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at D:\Projects\redux\redux-toolkit\node_modules\@docusaurus\core\lib\webpack\utils.js:180:24
```

**Comment by Josh-Cena** [comment]
@markerikson Could you open a new issue or ask in discussions? This issue has been resolved as a plugin polyfilling issue, so yours is probably unrelated. There are many, many things that can cause the `chalk` usage to be broken (I've hit it quite a few times.) I'm currently on vacation so I probably won't devote a lot of time to debug it until this weekend at least, so it's better if we can track it elsewhere.

**Comment by markerikson** [comment]
@Josh-Cena ok, will do!

**Comment by tfrijsewijk** [comment]
Leaving it here for fellow Googlers:

I was seeing this error because I had a `style="just-some-string-here" attribute in my .md file:

```html
<p style="background-color: #ebf3e6; width: 100%; height: 150px"></p>
```

I did the same that @markerikson did [here](https://github.com/facebook/docusaurus/issues/7398#issuecomment-1166661176) which resulted in the following build error:

```
Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
```

I went on searching for `style=` when I noticed the markup.

Thanks Mark for the initial hint!
