### ISSUE TITLE
Cannot import CSS from dependency module (importing local CSS is fine)

### ISSUE THREAD

**Issue by yechs** [facebook/docusaurus#7743]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Imported CSS from a dependency module has no effect, as if the `import` statement does not exist.
```javascript
import 'yet-another-react-lightbox/styles.css';
```

However, if I manually copy the css file to `/src/css/` directory and import it from here, it works.
```javascript
import '../../css/yarl.css';
```

I have created a reproducible demo in StackBlitz([link](https://stackblitz.com/edit/github-dyi68j?file=src%2Fpages%2Findex.js)). The relevant code is `/src/pages/index.js:L7-L10`.

If you wish to try out a larger demo, you can also observe the effect in my own repository (https://github.com/yechs/website/blob/gallery/src/components/Gallery/index.tsx#L6-L8)

### Reproducible demo

https://stackblitz.com/edit/github-dyi68j?file=src%2Fpages%2Findex.js

### Steps to reproduce

1. Run the code as is (importing CSS from the module)
2. Open the page, click on any of the images. Observe that the created div with className `yarl__portal yarl__portal_open` has no CSS corresponded to them
3. Uncomment the line `import '../css/yarl.css'`, which imports the CSS file from a local copy
4. Rerun the code
5. Open the page, click on any of the images. Observe that the lightbox now functions correctly with all the CSS styles.

### Expected behavior

All the CSS are correctly imported from the module.

### Actual behavior

No CSS is imported from the module, as if the import statement does not exist.

A hacky work-around is to manually copy the CSS to a local file and import from local file.

### Your environment

- Public source code: 
  - (see stackblitz) https://stackblitz.com/edit/github-dyi68j?file=src%2Fpages%2Findex.js
  - OR
  - https://github.com/yechs/website/blob/gallery/src/components/Gallery/index.tsx#L6-L8
- Public site URL: 
  - (see stackblitz)
  - OR
  - https://deploy-preview-71--yechs.netlify.app/gallery/
- Docusaurus version used: 
  - 2.0.0-beta.22, and can also be observed in 2.0.0-beta.21
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
  - Firefox 101 and Node v16.15.1
  - Firefox 101 and v16.14.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Note: seems fixed with `USE_SIMPLE_CSS_MINIFIER=true`

**Comment by yechs** [comment]
> 

Updated the [StackBlitz repro](https://stackblitz.com/edit/github-dyi68j?file=package.json) with the environment variable. Seems like it is still not working

**Comment by Josh-Cena** [comment]
I'm pretty convinced this is because they have `"sideEffects": false` in their package.json which causes the CSS side-effect-import to be tree-shaken:

https://github.com/igordanchenko/yet-another-react-lightbox/blob/50d21a70a769c5a8859effecd0e222bdc9ddadca/package.json#L62

Doesn't seem like a Docusaurus defect, so closing

**Comment by yechs** [comment]
Oops, you are perfectly right. I'll bring this over to the package maintainer of yet-another-react-lightbox. Really appreciate your help in pinpointing the problem!

**Comment by sekoyo** [comment]
> I'm pretty convinced this is because they have `"sideEffects": false` in their package.json which causes the CSS side-effect-import to be tree-shaken:
> 
> https://github.com/igordanchenko/yet-another-react-lightbox/blob/50d21a70a769c5a8859effecd0e222bdc9ddadca/package.json#L62
> 
> Doesn't seem like a Docusaurus defect, so closing

CSS is always a side effect, seems a shame to possibly reduce the tree shake-ability of a package just because it uses css?
