### ISSUE TITLE
Collapse sidebar button works strange.

### ISSUE THREAD

**Issue by mihilt** [facebook/docusaurus#8918]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

In https://docusaurus.io/docs, I can see collapse side bar button at the bottom left.
And when I collapse it, it turns weird.
The way to solve this problem is clicking menu that can expand.

I think bug happens because there is a problem between expand menu button and collapse side bar button.

https://user-images.githubusercontent.com/50368758/233884481-ad796d4e-a4c5-4be1-8548-72b19399e3cf.mp4

### Steps to reproduce

Visit https://docusaurus.io/docs and act like the video above.

### Expected behavior

It need to collapse and expand properly.

### Actual behavior

It works something weird.

### Your environment

- Public site URL: https://docusaurus.io/docs
- Docusaurus version used: Maybe latest version (2.4.0)
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/facebook/docusaurus/pull/8906

**Comment by slorber** [comment]
Oups, not fixed, can still reproduce this on our website, this is not supposed to happen:

<img width="1617" alt="CleanShot 2023-04-26 at 18 12 48@2x" src="https://user-images.githubusercontent.com/749374/234636971-aa885acb-1035-4c50-8b01-d4d8cb1e2425.png">

**Comment by mud1tx** [comment]
@mihilt I can work on this issue please assign it to me.

**Comment by mihilt** [comment]
@mud1tx I'm not the maintainer of this repository and I also don't have any permission to set someone in assignees.

**Comment by slorber** [comment]
@mud1tx if you want to contribute to little issues like this one the best is to send a PR directly. 

Unless the PR requires lots of code and a design phase it's better to show us some code asap.

I don't think this issue would have been so easy for an external contributor to fix, so I fixed it here already: https://github.com/facebook/docusaurus/pull/8971
